# Generated by Django 3.1.7 on 2021-04-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20210418_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
